In [1]:
import pandas as pd
import numpy as np

### 读写中文 CSV 示例

`utf-8-sig` 更适合在 Excel 中打开中文 CSV，避免中文乱码。

In [2]:
df_obj = pd.DataFrame({
    "编号": ["CNN001", "CNN002", "CNN003", "CNN004", "CNN005", "CNN006", "CNN007", "CNN008", "CNN009", "CNN010"],
    "姓名": ["小明", "小红", "小蓝", "小黑", "小白", "小方", "小梅", "小刚", "小丽", "小花"],
    "性别": ["男", "女", "女", "男", "男", "女", "女", "男", "女", "女"],
    "部门": ["行政", "人力资源", "销售", "研发", "财务", "技术", "", "市场", "研发", "技术"],
    "职务": ["员工", "主管", "员工", "主管", "员工", "员工", "员工", "员工", "主管", "员工"]
})

df_obj.to_csv("employee_info.csv", index=False, encoding="utf")
df_obj2 = pd.read_csv("employee_info.csv", encoding="utf")
df_obj2

       编号  姓名 性别    部门  职务
0  CNN001  小明  男    行政  员工
1  CNN002  小红  女  人力资源  主管
2  CNN003  小蓝  女    销售  员工
3  CNN004  小黑  男    研发  主管
4  CNN005  小白  男    财务  员工
5  CNN006  小方  女    技术  员工
6  CNN007  小梅  女   NaN  员工
7  CNN008  小刚  男    市场  员工
8  CNN009  小丽  女    研发  主管
9  CNN010  小花  女    技术  员工

### 一、基础创建与查看

1. 导入 pandas，用字典创建 DataFrame：

   name: Tom, Jerry, Mike

   score: 85, 92, 78

   gender: 男，女，男

2. 查看上述 DataFrame 的前 1 行、形状、列名、数据类型。

In [63]:
data_dict = {
    "name": ["Tom", "Jerry", "Mike"],
    "score": [85, 92, 78],
    "gender": ["男", "女", "男"]
}

df = pd.DataFrame(data_dict)
df

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [ ]:
df.head(1)

  name  score gender
0  Tom     85      男

In [ ]:
df.shape

(3, 3)

In [ ]:
df.columns

Index(['name', 'score', 'gender'], dtype='object')

In [ ]:
df.dtypes

name      object
score      int64
gender    object
dtype: object

3. 用列表创建 DataFrame：

   data = [[1, "A"], [2, "B"], [3, "C"]]

   列名设为 id、tag。

In [6]:
data = [[1, "A"], [2, "B"], [3, "C"]]
pd.DataFrame(data, columns=["id", "tag"])

   id tag
0   1   A
1   2   B
2   3   C

### 二、列与行操作

1. 选取 score 和 gender 两列。
2. 选取索引 0、2 的行。
3. 筛选 score > 80 的行。
4. 新增一列 grade：score ≥ 90 为优秀，否则为良好。
5. 删除 gender 列。

In [ ]:
df[["score", "gender"]]

   score gender
0     85      男
1     92      女
2     78      男

In [10]:
df.iloc[[0, 2]]

   name  score gender
0   Tom     85      男
2  Mike     78      男

In [ ]:
df[df["score"] > 80]

    name  score gender
0    Tom     85      男
1  Jerry     92      女

In [ ]:
df["grade"] = np.where(df["score"] >= 90, "优秀", "良好")
df

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

In [ ]:
df.drop(columns="gender")

    name  score grade
0    Tom     85    良好
1  Jerry     92    优秀
2   Mike     78    良好

### 三、缺失值

1. 创建含缺失值的 DataFrame：

   data = {"x": [1, None, 3], "y": [None, 5, 6]}

   检测缺失值并统计每列缺失数量。
2. 用 0 填充缺失值；删除含缺失值的行。

In [27]:
data_missing = {"x": [1, None, 3], "y": [None, 5, 6]}
df_missing = pd.DataFrame(data_missing)
df_missing

     x    y
0  1.0  NaN
1  NaN  5.0
2  3.0  6.0

In [26]:
df_missing.isna()

       x      y
0  False   True
1   True  False
2  False  False

In [ ]:
df_missing.isna().sum()

x    1
y    1
dtype: int64

In [64]:
df_missing.fillna(df_missing.mean())

     x    y
0  1.0  5.5
1  2.0  5.0
2  3.0  6.0

In [32]:
df_missing.dropna(axis=0, how="any")

     x    y
2  3.0  6.0

### 四、分组聚合

1. 按 gender 分组，求 score 的均值和最大值。
2. 按 gender 分组，统计每组人数。

In [40]:
df.groupby("gender")["score"].agg(["mean", "max"])

        mean  max
gender
女       92.0   92
男       81.5   85

In [ ]:
df.groupby("gender").size()

gender
女    1
男    2
dtype: int64

### 五、排序与去重

1. 按 score 升序排序。
2. 给 DataFrame 添加一行重复数据（如 Tom, 85, 男），去重。

In [61]:
df.sort_values(by="score", ascending=True)

    name  score gender
2   Mike     78      男
0    Tom     85      男
1  Jerry     92      女

In [47]:
df_with_dup = pd.concat([df, df.iloc[[0]]], ignore_index=True)
df_with_dup

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男
3    Tom     85      男

In [ ]:
df_with_dup.drop_duplicates()

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

### 六、合并与拼接

1. 横向合并：

   df1 = pd.DataFrame({"id": [1, 2], "name": ["X", "Y"]})

   df2 = pd.DataFrame({"id": [1, 2], "age": [20, 30]})

   按 id 合并。

In [53]:
df1 = pd.DataFrame({"id": [1, 2], "name": ["X", "Y"]})
df2 = pd.DataFrame({"id": [1, 2], "age": [20, 30]})

pd.merge(df1, df2, on="id")

   id name  age
0   1    X   20
1   2    Y   30

2. 纵向拼接：

   df_a = pd.DataFrame({"val": [1, 2]})

   df_b = pd.DataFrame({"val": [3, 4]})

   拼接后重置索引。

In [55]:
df_a = pd.DataFrame({"val": [1, 2]})
df_b = pd.DataFrame({"val": [3, 4]})

pd.concat([df_a, df_b], ignore_index=True)

   val
0    1
1    2
2    3
3    4

### 七、时间处理

1. 创建时间列：["2025-01-01", "2025-01-02", "2025-01-03"]，转为 datetime 格式。
2. 提取时间列的月份、星期。

In [57]:
df_time = pd.DataFrame({"date": ["2025-01-01", "2025-01-02", "2025-01-03"]})
df_time["date"] = pd.to_datetime(df_time["date"])
df_time

        date
0 2025-01-01
1 2025-01-02
2 2025-01-03

In [59]:
weekday_map = {
    0: "星期一",
    1: "星期二",
    2: "星期三",
    3: "星期四",
    4: "星期五",
    5: "星期六",
    6: "星期日"
}

df_time["month"] = df_time["date"].dt.month
df_time["weekday"] = df_time["date"].dt.dayofweek.map(weekday_map)
df_time

        date  month weekday
0 2025-01-01      1     星期三
1 2025-01-02      1     星期四
2 2025-01-03      1     星期五

### 八、高级操作

1. 对 score 列做标准化：`(值 - 均值) / 标准差`。
2. 用透视表：行是 gender，值是 score，聚合函数为中位数。

In [ ]:
df["score_standardized"] = (df["score"] - df["score"].mean()) / df["score"].std()
df

    name  score gender grade  score_standardized
0    Tom     85      男    良好                 0.0
1  Jerry     92      女    优秀                 1.0
2   Mike     78      男    良好                -1.0

In [ ]:
pd.pivot_table(df, index="gender", values="score", aggfunc="median")

        score
gender
女        92.0
男        81.5